In [3]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-2.0.0-py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.macosx_12_0_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 5.4 MB/s eta 0:00:00a 0:00:010m
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.9/site-packages (from xgboost) (1.9.1)
Installing collected packages: xgboost
Successfully installed xgboost-2.0.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, RandomizedSearchCV, TimeSeriesSplit
from sklearn.metrics import mean_absolute_error

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

In [2]:
RANDOM_STATE = 123

In [3]:
data = pd.read_csv('data/train_dataset.csv')

In [4]:
data.head()

         date  time   target  temp  temp_pred weather_pred weather_fact
0  2019-01-01     0  481.510   2.9        2.0  пасм, ветер        ветер
1  2019-01-01     1  462.872   2.9        2.0  пасм, ветер        ветер
2  2019-01-01     2  449.718   2.9        2.0  пасм, ветер        ветер
3  2019-01-01     3  430.908   4.3        2.0  пасм, ветер  ветер, пасм
4  2019-01-01     4  415.163   4.3        2.0  пасм, ветер  ветер, пасм

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37224 entries, 0 to 37223
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          37224 non-null  object
 1   time          37224 non-null  int64
 2   target        37224 non-null  float64
 3   temp          37224 non-null  float64
 4   temp_pred     37136 non-null  float64
 5   weather_pred  37136 non-null  object
 6   weather_fact  37223 non-null  object
dtypes: float64(3), int64(1), object(3)
memory usage: 2.0+ MB

In [6]:
data['date'] = pd.to_datetime(data['date'])

In [7]:
data['day'] = data['date'].dt.day
data['month'] = data['date'].dt.month
data['year'] = data['date'].dt.year
data['day_of_week'] = data['date'].dt.dayofweek

In [8]:
data.head()

,date,time,target,temp,temp_pred,weather_pred,weather_fact,day,month,year,day_of_week
0,2019-01-01,0,481.510,2.9,2.0,"пасм, ветер",ветер,1,1,2019,1
1,2019-01-01,1,462.872,2.9,2.0,"пасм, ветер",ветер,1,1,2019,1
2,2019-01-01,2,449.718,2.9,2.0,"пасм, ветер",ветер,1,1,2019,1
3,2019-01-01,3,430.908,4.3,2.0,"пасм, ветер","ветер, пасм",1,1,2019,1
4,2019-01-01,4,415.163,4.3,2.0,"пасм, ветер","ветер, пасм",1,1,2019,1

In [9]:
data['weather_pred'] = data['weather_pred'].astype('str')

In [10]:
data['predicted_weather'] = data['weather_pred'].str.split(',')

In [11]:
data.head()

,date,time,target,temp,temp_pred,weather_pred,weather_fact,day,month,year,day_of_week,predicted_weather
0,2019-01-01,0,481.510,2.9,2.0,"пасм, ветер",ветер,1,1,2019,1,"[пасм, ветер]"
1,2019-01-01,1,462.872,2.9,2.0,"пасм, ветер",ветер,1,1,2019,1,"[пасм, ветер]"
2,2019-01-01,2,449.718,2.9,2.0,"пасм, ветер",ветер,1,1,2019,1,"[пасм, ветер]"
3,2019-01-01,3,430.908,4.3,2.0,"пасм, ветер","ветер, пасм",1,1,2019,1,"[пасм, ветер]"
4,2019-01-01,4,415.163,4.3,2.0,"пасм, ветер","ветер, пасм",1,1,2019,1,"[пасм, ветер]"

In [ ]:
df['weather_pred']